name: CI

on:
  push:
    branches:
      - main     

  pull_request:
    branches:
      - main     

jobs:
  test:
    # change to ubuntu-latest once Ruby 2.5 and JRuby 9.2 is dropped
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, jruby-9.1, jruby-9.2, jruby-9.3, jruby-9.4]
        env: [NEW_RAILS, OLD_RAILS]

    steps:
      - name: Setup     
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Environment 
        run: echo "${{ matrix.env }}=1" >> $GITHUB_ENV

      - name: Install     
        run: |
          echo NEW_RAIS=$NEW_RAILS OLD_RAILS=$OLD_RAILS   
          bundle install --without docs     

      - name: Test 
        run: bundle exec rake release:test

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: Rubocop
        run: bundle exec rubocop -E -S